/**
 * The purpose of this file is to provide an interface to contain the errors
 * generated by the compiler
 */

public class Error{
    public String type;
    public String cause;
    public String suggestion;
    public Token errorToken;

    public Error(String type, String cause, String suggestion){
        this.type = type;
        this.cause = cause;
        this.suggestion = suggestion;
    }

    public void setErrorToken(Token errorToken){
        this.errorToken = errorToken;
    }

    public String toString(){
        String result = "";
        result += "--------------------------------------------------\n";
        result += this.type + " ERROR:\n";
        if (this.errorToken != null){
            result += "FILE: " + this.errorToken.filename + "\n";
            result += "LINE: " + this.errorToken.lineNumber + "\n";
        }
        result += "CAUSE:\n";
        result += "\t" + this.cause + "\n";
        result += "SUGGESTIONS:\n";
        result += "\t" + this.suggestion + "\n";

        return result;
    }
}
